### ISSUE TITLE
[Native-Image] Port is not freed under Rosetta 2

### ISSUE THREAD

**Issue by KevinRoebert** [drasyl/drasyl#203]
Under Rosetta 2, hard kills in the native image cause the allocated ports not to be released and assigned to a process that no longer exists. The only workaround is to restart the operating system.

Possibly https://github.com/oracle/graal/issues/2666 is a fix for the problem.

**Comment by lewurm** [comment]
> Under Rosetta 2, hard kills in the native image cause the allocated ports not to be released and assigned to a process that no longer exists. The only workaround is to restart the operating system.

Hu, that sounds awful and probably worth reporting to Apple. Could you share steps to reproduce?

**Comment by KevinRoebert** [comment]
Looks like the port will not be released again either if a native library is built. Even without Rosetta 2.

**Comment by KevinRoebert** [comment]
Maybe related to:

- https://github.com/docker/for-mac/issues/205
- https://serverfault.com/questions/1083124/netstat-reports-udp-ports-with-no-owning-process/1093665#1093665

**Comment by KevinRoebert** [comment]
Interesting fact: If the MacOS firewall is disabled, the error does not occur.
