### ISSUE TITLE
Add NP check to SntpClient

### ISSUE THREAD

**Issue by HeikoBornholdt** [drasyl/drasyl#587]
Der @KevinRoebert,

https://github.com/drasyl/drasyl/blob/master/drasyl-extras/src/main/java/org/drasyl/handler/sntp/SntpClient.java#L47 is calling `NetworkUtil.getDefaultGateway()`. It is [well documented](https://github.com/drasyl/drasyl/blob/master/drasyl-core/src/main/java/org/drasyl/util/network/NetworkUtil.java#L316) that this method might return `null`. Your code fails if this is the case.

**Comment by KevinRoebert** [comment]
funny guy

**Comment by KevinRoebert** [comment]
please make a PR
